Repository pivotal-cf/brokerapi, pull requests merged in 2021-03, with the labels that each got.

#139 feat: plan_updateable is missing from ServicePlan
  domain/service_catalog.go
  domain/service_catalog_test.go
  v7/domain/service_catalog.go
Labels: scheduled

#149 Revert "Add the request identity to the context"
  README.md
  api.go
  api_test.go
  middlewares/request_identity_header.go
Labels: unscheduled

#148 Implement `X-Broker-API-Originating-Identity`
  README.md
  api.go
  api_test.go
  handlers/api_handler.go
  handlers/bind.go
  handlers/catalog.go
  handlers/deprovision.go
  handlers/get_binding.go
  handlers/get_instance.go
  handlers/last_binding_operation.go
  handlers/last_operation.go
  handlers/provision.go
  handlers/unbind.go
  handlers/update.go
  middlewares/api_version_header.go
  middlewares/request_identity_header.go
  v7/api.go
  v7/handlers/api_handler.go
  v7/handlers/bind.go
  v7/handlers/catalog.go
  v7/handlers/deprovision.go
  v7/handlers/get_binding.go
  v7/handlers/get_instance.go
  v7/handlers/last_binding_operation.go
  v7/handlers/last_operation.go
  v7/handlers/provision.go
  v7/handlers/unbind.go
  v7/handlers/update.go
  v7/middlewares/api_version_header.go
  v7/middlewares/request_identity_header.go
Labels: scheduled

#147 Nicky mateev osb fetch details
  api_test.go
  domain/service_broker.go
  fakes/auto_fake_service_broker.go
  fakes/fake_service_broker.go
  handlers/get_binding.go
  handlers/get_instance.go
  v7/domain/service_broker.go
  v7/handlers/get_binding.go
  v7/handlers/get_instance.go
Labels: in progress
